import js from "@eslint/js";
import typescriptPlugin from "@typescript-eslint/eslint-plugin";
import typescriptParser from "@typescript-eslint/parser";
import qwikPlugin from "eslint-plugin-qwik";
import globals from "globals";

export default [
  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
      },
      parser: typescriptParser,
      parserOptions: {
        tsconfigRootDir: process.cwd(),
        project: ["./tsconfig.json"],
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    plugins: {
      "@typescript-eslint": typescriptPlugin,
      qwik: qwikPlugin,
    },
    rules: {
      "prefer-spread": "off",
      "no-case-declarations": "off",
      "no-console": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      "@typescript-eslint/no-inferrable-types": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-empty-interface": "off",
      "@typescript-eslint/no-namespace": "off",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/no-this-alias": "off",
      "@typescript-eslint/ban-types": "off",
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/no-unused-vars": ["error"],
      "@typescript-eslint/consistent-type-imports": "warn",
      "@typescript-eslint/no-unnecessary-condition": "warn",
    },
    ignores: [
      '**/*.log',
      '**/.DS_Store',
      '*.',
      '.vscode/settings.json',
      '.history',
      '.yarn',
      'bazel-*',
      'bazel-bin',
      'bazel-out',
      'bazel-qwik',
      'bazel-testlogs',
      'dist',
      'dist-dev',
      'lib',
      'lib-types',
      'etc',
      'external',
      'node_modules',
      'temp',
      'tsc-out',
      'tsdoc-metadata.json',
      'target',
      'output',
      'rollup.config.js',
      'build',
      '.cache',
      '.vscode',
      '.rollup.cache',
      'dist',
      'tsconfig.tsbuildinfo',
      'vite.config.ts',
      '*.spec.tsx',
      '*.spec.ts',
      '.netlify',
      'pnpm-lock.yaml',
      'package-lock.json',
      'yarn.lock',
      'server',
    ],
  },
];